apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: todo-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: faizananjum12/backend:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8007
        envFrom:
        - secretRef:
            name: todo-app-secrets
